// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Employee struct {
	ID       int64  `json:"id"`
	Name     string `json:"name"`
	Position string `json:"position"`
	// must be positive
	Salary    float64          `json:"salary"`
	CreatedAt pgtype.Timestamp `json:"created_at"`
}
