// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	CreateEmployee(ctx context.Context, arg CreateEmployeeParams) (Employee, error)
	DeleteEmployee(ctx context.Context, id int64) error
	GetEmployeeByID(ctx context.Context, id int64) (Employee, error)
	GetEmployeeForUpdate(ctx context.Context, id int64) (Employee, error)
	UpdateEmployee(ctx context.Context, arg UpdateEmployeeParams) (Employee, error)
}

var _ Querier = (*Queries)(nil)
